# https://www.mkdocs.org/getting-started/#theming-our-documentation
# https://squidfunk.github.io/mkdocs-material/creating-your-site/
# https://squidfunk.github.io/mkdocs-material/reference/

site_name: xLH xemax Learning Hub Konzeptstudie
site_url: https://www.xlh.xemax.ch

nav:
  - xLH:
    - Didaktisches Konzept: index.md
    - HK - LF - Orientierung: 1000_xlh/1000_hkp_lfe_orientierung.md

  - Umsetzungsbeispiele:
    - SPS Einführung: 2000_beispiele/1000_sps.md
    - Portalroboter: 2000_beispiele/2000_portalroboter.md
    - Thermoversuch: 2000_beispiele/3000_thermoversuch.md

  - Installation & IBN:
    - Programminstallation: 3000_installation_ibn/1000_installation.md
    - Inbetriebnahme xLH_base: 3000_installation_ibn/2000_inbetriebnahme_xlh.md

extra_css:
  - stylesheets/extra.css

theme:
  name: material
  custom_dir: ../overrides
  logo: assets/icon/xemax.svg
  favicon: assets/icon/xemax.ico
  navigation_depth: 4
  icon:
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
    annotation: material/plus-circle
    admonition:
      note: octicons/info-16
  features:
#    - toc.integrate
    - toc.follow
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
#    - navigation.instant.prefetch
#    - navigation.instant.progress
    - navigation.tracking
#    - navigation.sections

    - navigation.expand

    - navigation.indexes
    - navigation.path
    - search.suggest
    - search.highlight
    - search.share
#    - content.code.annotation
    - content.code.copy
    - content.tooltips
#    - header.autohide

  language: de

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Umschaltung in die dunkle Darstellung

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Umschaltung in die helle Darstellung

markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      auto_append:
        - includes/glossar.md
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
#  - pymdownx.magiclink
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.mark
  - abbr
  - attr_list
  - md_in_html
  - tables
#  - toc:
#      toc_depth: 4
#      permalink: true
#  - pymdownx.arithmatex:
#      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

copyright: |
  27.09.2024 - <a href="#__consent">Anpassung der Cookie-Richtlinien</a> - &copy; <a href="https://www.xemax.ch"  target="_blank" rel="noopener">xemax ag</a>

plugins:
  - search
  - exclude-search:
      exclude:
        - playground/*
        - data/*
#  - mkdocs-jupyter:
#      execute: true
#      allow_errors: false
#      kernel_name: python3
#      include_requirejs: true
#      show_input: false
#      no_input: true
#  - privacy
#  - glightbox

extra:
  homepage: https://xemax.ch
  analytics:
      provider: google
      property: G-5LVJ0HCXXY
  consent:
    title: Cookie-Richtlinien
    description: Wir verwenden Cookies, um Ihre wiederholten Besuche und Präferenzen zu erkennen, sowie um die Effektivität unserer Dokumentation zu messen und um festzustellen, ob die Nutzer finden, wonach sie suchen. Mit Ihrer Zustimmung helfen Sie uns, unsere Dokumentation zu verbessern.
    actions:
      - accept
      - reject
      - manage
    analytics:
      name: Google Analytics
      checked: true